### PR TITLE
Ui cards

### PR DESCRIPTION
**Pull request by dougajmcdonald**
Updated the UI to make better use of the map, implemented cards for results and insights and then tweaked the paddings etc.

Also made the font sizes relative to the resolution so it scales for smaller devices.

image

image

image

image

### CODE REVIEW

**Comment by conradj** [comment]
🎉 🔥 😎

**Comment by conradj** [comment]
[#bb0b530](https://github.com/bmtwebdevs/tradeoff/pull/24/commits/bb0b530409d2e0df74449c2f4d3f57f448a92538)

tradeoff

**Comment by gillyhl** [comment]
ahhhh this may clash with the mobile css D:

**Comment by dougajmcdonald** [comment]
If only there was some way we could have programmed as a group and avoided such a conflict! ...

**Pull request merged**
